export const GET_ALL_USER_ACCOUNT = "account/GET_ALL_USER_ACCOUNT";
export const GET_ALL_USER_ACCOUNT_COMPLETED = "account/GET_ALL_USER_ACCOUNT_COMPLETED";
export const ADD_NEW_USER_ACCOUNT = "account/ADD_NEW_USER_ACCOUNT";
export const UPDATE_USER_ACCOUNT = "account/UPDATE_USER_ACCOUNT";
export const DELETE_USER_ACCOUNT = "account/DELETE_USER_ACCOUNT";