export const GET_ALL_CLASS_BY_ID_COURSE = "class/GET_ALL_CLASS_BY_ID_COURSE";
export const GET_ALL_CLASS_BY_ID_COURSE_COMPLETED = "class/GET_ALL_CLASS_BY_ID_COURSE_COMPLETED";
export const GET_ALL_CLASS_BY_ID_COURSE_FAILED = "class/GET_ALL_CLASS_BY_ID_COURSE_FAILED";

export const ADD_NEW_CLASS = "class/ADD_NEW_CLASS";
export const ADD_NEW_CLASS_COMPLETED = "class/ADD_NEW_CLASS_COMPLETED";
export const ADD_NEW_CLASS_FAILED = "class/ADD_NEW_CLASS_FAILED";

export const UPDATE_CLASS = "class/UPDATE_CLASS";
export const UPDATE_CLASS_COMPLETED = "class/UPDATE_CLASS_COMPLETED";
export const UPDATE_CLASS_FAILED = "class/UPDATE_CLASS_FAILED";

export const DELETE_CLASS = "class/DELETE_CLASS";
export const DELETE_CLASS_COMPLETED = "class/DELETE_CLASS_COMPLETED";
export const DELETE_CLASS_FAILED = "class/DELETE_CLASS_FAILED";

export const GET_CLASS_BY_ID = "class/GET_CLASS_BY_ID";
export const GET_CLASS_BY_ID_COMPLETED = "class/GET_CLASS_BY_ID_COMPLETED";
export const GET_CLASS_BY_ID_FAILED = "class/GET_CLASS_BY_ID_FAILED";