export const FETCH_LIST_BANNER = "banner/FETCH_LIST_BANNER";
export const FETCH_LIST_BANNER_COMPLETED = "banner/FETCH_LIST_BANNER_COMPLETED";
export const FETCH_LIST_BANNER_FAILED = "banner/FETCH_LIST_BANNER_FAILED";