export const GET_ALL_COURSE_BY_ID_YEAR = "course/GET_ALL_COURSE_BY_ID_YEAR";
export const GET_ALL_COURSE_BY_ID_YEAR_COMPLETED = "course/GET_ALL_COURSE_BY_ID_YEAR_COMPLETED";
export const GET_ALL_COURSE_BY_ID_YEAR_FAILED = "course/GET_ALL_COURSE_BY_ID_YEAR_FAILED";

export const ADD_NEW_COURSE = "course/ADD_NEW_COURSE";
export const ADD_NEW_COURSE_COMPLETED = "course/ADD_NEW_COURSE_COMPLETED";
export const ADD_NEW_COURSE_FAILED = "course/ADD_NEW_COURSE_FAILED";

export const UPDATE_COURSE = "course/UPDATE_COURSE";
export const UPDATE_COURSE_COMPLETED = "course/UPDATE_COURSE_COMPLETED";
export const UPDATE_COURSE_FAILED = "course/UPDATE_COURSE_FAILED";

export const DELETE_COURSE = "course/DELETE_COURSE";
export const DELETE_COURSE_COMPLETED = "course/DELETE_COURSE_COMPLETED";
export const DELETE_COURSE_FAILED = "course/DELETE_COURSE_FAILED";

export const OPEN_EDIT_COURSE = "course/OPEN_EDIT_COURSE";
export const CLOSE_EDIT_COURSE = "course/CLOSE_EDIT_COURSE";

export const GET_COURSE_BY_ID = "course/GET_COURSE_BY_ID";
export const GET_COURSE_BY_ID_COMPLETED = "course/GET_COURSE_BY_ID_COMPLETED";
export const GET_COURSE_BY_ID_FAILED = "course/GET_COURSE_BY_ID_FAILED";

export const GET_ALL_COURSE_BY_MAX_CLASSES = "course/GET_ALL_COURSE_BY_MAX_CLASSES";
export const GET_ALL_COURSE_BY_MAX_CLASSES_COMPLETED = "course/GET_ALL_COURSE_BY_MAX_CLASSES_COMPLETED";
export const GET_ALL_COURSE_BY_MAX_CLASSES_FAILED = "course/GET_ALL_COURSE_BY_MAX_CLASSES_FAILED";

export const SELECT_COURSE = "course/SELECT_COURSE";